/**
 * Léxicos curados de intención por idioma (V5.5). DATOS separados de la lógica
 * del parser. Estrechos, intencionales y probables. Cada intención tiene al
 * menos una frase en cada uno de los 7 idiomas. No es un diccionario
 * incontrolado ni pretende entender lenguaje libre.
 */
import type { SupportedLocale } from '../i18n/types';
import type { IntentId } from './intentModel';

/** Frases crudas por intención e idioma (se normalizan en el parser). */
export const INTENT_LEXICON: Readonly<Record<IntentId, Record<SupportedLocale, string[]>>> = {
  BREAKFAST: {
    es: ['desayuno', 'desayunar', 'algo para desayunar'],
    en: ['breakfast', 'breakfast place', 'get breakfast'],
    pt: ['café da manhã', 'tomar café da manhã'],
    fr: ['petit déjeuner', 'petit-déjeuner'],
    it: ['colazione', 'fare colazione'],
    de: ['frühstück', 'frühstücken'],
    'zh-CN': ['早餐', '早饭'],
  },
  COFFEE: {
    es: ['café', 'cafetería'],
    en: ['coffee', 'coffee shop'],
    pt: ['café', 'cafeteria'],
    fr: ['café', 'un café'],
    it: ['caffè', 'un caffè'],
    de: ['kaffee', 'café'],
    'zh-CN': ['咖啡', '喝咖啡'],
  },
  LUNCH: {
    es: ['almuerzo', 'comida', 'almorzar'],
    en: ['lunch', 'get lunch'],
    pt: ['almoço', 'almoçar'],
    fr: ['déjeuner', 'le déjeuner'],
    it: ['pranzo', 'pranzare'],
    de: ['mittagessen'],
    'zh-CN': ['午餐', '午饭'],
  },
  DINNER: {
    es: ['cena', 'cenar'],
    en: ['dinner', 'get dinner'],
    pt: ['jantar'],
    fr: ['dîner', 'le dîner'],
    it: ['cena', 'cenare'],
    de: ['abendessen'],
    'zh-CN': ['晚餐', '晚饭'],
  },
  NIGHTLIFE: {
    es: ['vida nocturna', 'antro', 'bar'],
    en: ['nightlife', 'bar'],
    pt: ['vida noturna', 'bar'],
    fr: ['vie nocturne', 'bar'],
    it: ['vita notturna', 'bar'],
    de: ['nachtleben', 'bar'],
    'zh-CN': ['夜生活', '酒吧'],
  },
  FAMILY_ACTIVITY: {
    es: ['familia', 'familiar', 'para la familia'],
    en: ['family', 'for the family'],
    pt: ['família', 'para a família'],
    fr: ['famille', 'en famille'],
    it: ['famiglia', 'in famiglia'],
    de: ['familie', 'für die familie'],
    'zh-CN': ['家庭', '带家人'],
  },
  QUICK_STOP: {
    es: ['algo rápido', 'parada rápida', 'rápido'],
    en: ['quick stop', 'something quick', 'quick'],
    pt: ['algo rápido', 'parada rápida'],
    fr: ['quelque chose de rapide', 'rapide'],
    it: ['qualcosa di veloce', 'veloce'],
    de: ['etwas schnelles', 'schnell'],
    'zh-CN': ['便利店', '快速'],
  },
  SHOPPING: {
    es: ['compras', 'ir de compras', 'tienda'],
    en: ['shopping', 'store'],
    pt: ['compras', 'loja'],
    fr: ['achats', 'magasin'],
    it: ['spesa', 'negozio'],
    de: ['einkaufen', 'geschäft'],
    'zh-CN': ['购物', '商店'],
  },
  PHARMACY: {
    es: ['farmacia'],
    en: ['pharmacy', 'drugstore'],
    pt: ['farmácia'],
    fr: ['pharmacie'],
    it: ['farmacia'],
    de: ['apotheke'],
    'zh-CN': ['药店', '药房'],
  },
  MEDICAL: {
    es: ['medicina', 'medicamento', 'necesito medicina'],
    en: ['medicine', 'medical help'],
    pt: ['remédio', 'médico'],
    fr: ['médicament', 'aide médicale'],
    it: ['medicina', 'farmaco'],
    de: ['medikament', 'medizin'],
    'zh-CN': ['买药', '看病'],
  },
  FUEL: {
    es: ['gasolina', 'gasolinera', 'combustible'],
    en: ['gas station', 'gas', 'fuel'],
    pt: ['gasolina', 'combustível'],
    fr: ['essence', 'carburant'],
    it: ['benzina', 'carburante'],
    de: ['tankstelle', 'benzin'],
    'zh-CN': ['加油站', '加油'],
  },
  LODGING: {
    es: ['hotel', 'hospedaje', 'alojamiento'],
    en: ['hotel', 'place to stay', 'lodging'],
    pt: ['hotel', 'hospedagem'],
    fr: ['hôtel', 'hébergement'],
    it: ['hotel', 'alloggio'],
    de: ['hotel', 'unterkunft'],
    'zh-CN': ['酒店', '旅馆'],
  },
  ENTERTAINMENT: {
    es: ['algo divertido', 'diversión'],
    en: ['something fun', 'fun', 'entertainment'],
    pt: ['algo divertido', 'diversão'],
    fr: ['quelque chose d amusant', 'sortir'],
    it: ['qualcosa di divertente', 'divertimento'],
    de: ['etwas spaßiges', 'unterhaltung'],
    'zh-CN': ['好玩的', '娱乐'],
  },
  ACCESSIBLE: {
    es: ['accesible', 'silla de ruedas'],
    en: ['accessible', 'wheelchair'],
    pt: ['acessível', 'cadeira de rodas'],
    fr: ['accessible', 'fauteuil roulant'],
    it: ['accessibile', 'sedia a rotelle'],
    de: ['barrierefrei', 'rollstuhl'],
    'zh-CN': ['无障碍', '轮椅'],
  },
  OPEN_NOW: {
    es: ['abierto ahora', 'abierto'],
    en: ['open now', 'open'],
    pt: ['aberto agora', 'aberto'],
    fr: ['ouvert maintenant', 'ouvert'],
    it: ['aperto ora', 'aperto'],
    de: ['jetzt geöffnet', 'geöffnet'],
    'zh-CN': ['正在营业', '营业中'],
  },
  OPEN_LATE: {
    es: ['abierto tarde', 'hasta tarde'],
    en: ['open late', 'late night'],
    pt: ['aberto até tarde', 'até tarde'],
    fr: ['ouvert tard', 'tard le soir'],
    it: ['aperto fino a tardi', 'fino a tardi'],
    de: ['spät geöffnet', 'lange geöffnet'],
    'zh-CN': ['营业到很晚', '深夜营业'],
  },
  NEARBY: {
    es: ['cerca de mí', 'cerca', 'cercano'],
    en: ['near me', 'nearby', 'close'],
    pt: ['perto de mim', 'perto', 'próximo'],
    fr: ['à proximité', 'proche', 'près'],
    it: ['nelle vicinanze', 'vicino'],
    de: ['in der nähe', 'nahe'],
    'zh-CN': ['离我近', '附近'],
  },
};
